# Generated by Django 4.2.6 on 2024-04-02 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/brand_images')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='static/category_images')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='static/subcat_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/product_images')),
                ('slug', models.SlugField()),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('detail', models.TextField(max_length=3000)),
                ('weight', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=15)),
                ('specifications', models.TextField(max_length=2000)),
                ('model', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.rating')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='category_front_page',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/category_front_page')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category')),
            ],
        ),
    ]
