# Generated by Django 4.2.6 on 2024-04-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('review', models.TextField(max_length=500)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.rating')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.review'),
        ),
    ]
