# Generated by Django 4.2.6 on 2024-04-04 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shop_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
