# Generated by Django 4.2.6 on 2024-04-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_brand_slug_remove_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_front_page',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
