# Generated by Django 4.2.6 on 2024-04-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='items_left',
            field=models.IntegerField(default=10, max_length=100),
        ),
    ]
