# Generated by Django 4.2.6 on 2024-04-07 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_items_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='items_left',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
