# Generated by Django 4.2.6 on 2024-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_items_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='hello-world', verbose_name='djangodbmodelsfieldscharfield'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='hello-world', verbose_name='djangodbmodelsfieldscharfield'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='hello-world', verbose_name='djangodbmodelsfieldscharfield'),
        ),
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default='hello-world', verbose_name='djangodbmodelsfieldscharfield'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='hello-world', verbose_name='djangodbmodelsfieldscharfield'),
        ),
    ]
