# Generated by Django 4.2.6 on 2024-04-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_brand_slug_category_slug_product_slug_shop_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='hello-world', unique=True, verbose_name='djangodbmodelsfieldscharfield'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='hello-world', unique=True, verbose_name='djangodbmodelsfieldscharfield'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='hello-world', unique=True, verbose_name='djangodbmodelsfieldscharfield'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default='hello-world', unique=True, verbose_name='djangodbmodelsfieldscharfield'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='hello-world', unique=True, verbose_name='djangodbmodelsfieldscharfield'),
        ),
    ]
