# Generated by Django 4.2.6 on 2024-04-21 22:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
