# Generated by Django 5.0.6 on 2024-06-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_secodary_id_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_location',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='djangodbmodelsfieldscharfield'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='djangodbmodelsfieldscharfield'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='djangodbmodelsfieldscharfield'),
        ),
    ]
