# Generated by Django 4.2.6 on 2024-04-21 23:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
