# Generated by Django 4.2.6 on 2024-04-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_descr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descr',
        ),
    ]
