# Generated by Django 4.2.6 on 2024-05-01 01:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
