# Generated by Django 4.2.6 on 2024-05-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='djangodbmodelsfieldscharfield'),
        ),
    ]
