# Generated by Django 4.2.6 on 2024-05-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='djangodbmodelsfieldscharfield'),
        ),
    ]
