# Generated by Django 5.0.6 on 2024-06-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_product_image1_product_image2_product_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/brand_images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/category_images'),
        ),
        migrations.AlterField(
            model_name='category_front_page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/category_front_page'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/subcat_images'),
        ),
    ]
