# Generated by Django 5.0.6 on 2024-07-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='order_id',
            new_name='cart_id',
        ),
    ]
