# Generated by Django 5.0.6 on 2024-07-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_rename_order_id_cart_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='public_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=160)),
                ('last_name', models.CharField(max_length=160)),
                ('phone_number', models.CharField(max_length=20)),
                ('region', models.CharField(choices=[('Eastern Region', 'Eastern Region'), ('Western Region', 'Western Region'), ('Nothern Region', 'Nothern Region'), ('Southern Region', 'Southern Region')], max_length=160)),
                ('city', models.CharField(default='Kampala', max_length=160)),
                ('address', models.CharField(max_length=255)),
                ('product_id', models.UUIDField()),
                ('product_name', models.CharField(max_length=255)),
            ],
        ),
    ]
