# Generated by Django 5.0.6 on 2024-07-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_public_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_cart',
            name='product_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='public_cart',
            name='region',
            field=models.CharField(choices=[('Central Region', 'Central Region'), ('Eastern Region', 'Eastern Region'), ('Western Region', 'Western Region'), ('Nothern Region', 'Nothern Region'), ('Southern Region', 'Southern Region')], max_length=160),
        ),
    ]
