# Generated by Django 5.0.6 on 2024-07-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_public_cart_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_cart',
            name='product_id',
            field=models.UUIDField(),
        ),
    ]
