# Generated by Django 5.1.5 on 2025-01-27 07:42

import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_product_seo_description_product_seo_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='other_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secodary_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=2000)),
                ('brand', models.CharField(max_length=500)),
                ('discount', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=999)),
                ('category2', models.CharField(max_length=999)),
                ('category3', models.CharField(max_length=999)),
                ('category4', models.CharField(max_length=999)),
                ('category5', models.CharField(max_length=999)),
                ('price', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('specifications', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='static/product_images')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='static/product_images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='static/product_images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='static/product_images')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
