# Generated by Django 5.1.5 on 2025-03-01 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_other_products_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2000, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='other_products',
            name='items_left',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='other_products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='other_products',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
